// 손으로 그린 32×32 유닛 마스터 (ART = 2 격자, sprites.js 의 계약을 따른다).
// 맵은 gfx2 생성기(units32.py)에서 put() 으로 짜서 옮겨 왔다. 고칠 때는 여기를 바로 고쳐도 된다.
// 글자 → 4단 램프 (밝은 면 / 바탕 / 그늘 / 깊은 그늘), 빛은 왼쪽 위:
//   등급 천  l c C 3      금속  1 m M 2 (전설 → 금, 신화 → 진주)   피부 s S 5 (+ v 볼)
//   눈 e (+ w 반짝임)       머리 6 h H 7     가죽·나무 9 b B 8        금장식 y g G 0
//   칼날 w W x             초록 옷 Q n N q   검은 옷 J k K j          보주 v p P
//   얼음 z i I Z (+ X 얼음관)  활 u U       후광 Y      날개 F f d (도적은 D d)
// layers: { min: 등급, x, y, rows, under } — min 등급부터 덧그린다. under 는 빈 칸에만 (망토·날개·후광).
// emis: 등급별 빛나는 글자 → '_e' 마스크 (블룸용).
(function (RS) {
  'use strict';
  if (!RS.defSprite) return;
  const shift = RS.shiftColor;

  const BASE = {
    1: '#f4f7fb', m: '#c9d3e0', M: '#8b97ab', 2: '#5a6378',
    s: '#f6caa5', S: '#d99b7e', 5: '#b4766a', v: '#f2a0a0', e: '#22192e',
    6: '#a8704a', h: '#7a4a32', H: '#4f2d20', 7: '#33190f',
    9: '#b07a52', b: '#8d5b3d', B: '#5e3b29', 8: '#3d2418',
    y: '#ffe46b', g: '#f5c44a', G: '#b5832b', 0: '#7a5418',
    w: '#fbf7ef', W: '#b8c2d3', x: '#7d8799',
    Q: '#9be08a', n: '#62c35f', N: '#2f7a3e', q: '#1f5230',
    J: '#5a4b7a', k: '#3d3158', K: '#282040', j: '#211a36',
    p: '#a061e8', P: '#5e3593',
    z: '#effcff', i: '#a8ecff', I: '#52b6e0', Z: '#2f7fb0', X: '#f4feff',
    u: '#b07a52', U: '#6e4127',
    Y: '#fff1a8', F: '#ffffff', f: '#f1dbe8', d: '#c792b2', D: '#7a2f55',
  };
  // 전설: 금속이 금으로, 신화: 진주빛 + 분홍 칼날
  const GOLD = { 1: '#fff7d6', m: '#f2d47e', M: '#c4943a', 2: '#7d5522' };
  const PEARL = { 1: '#ffffff', m: '#f4e6f0', M: '#c79cbc', 2: '#7c4a70', w: '#fff4f8', W: '#ffc2d6', x: '#e0789e' };
  const CLASS_PAL = {
    archer: (t) => (t >= 4 ? { u: '#ffd6e4', U: '#d65a8a' } : t >= 3 ? { u: '#ffe46b', U: '#c08a2e' } : {}),
    mage: (t) => (t >= 4 ? { v: '#ffffff', p: '#ff9ec0', P: '#d0407a' } : t >= 3 ? { v: '#ffffff', p: '#ffe46b', P: '#e0a030' } : {}),
    rogue: (t) => Object.assign({ v: '#f2a0a0', d: '#3a1530' }, t >= 4 ? { e: '#ff3d6e' } : t >= 3 ? { w: '#fff6c8', W: '#f0c040', x: '#b07a20' } : {}),
    frost: (t) => (t >= 4 ? { e: '#38d8ff' } : {}),
  };
  function pal(name) {
    return function (tier, T) {
      const p = Object.assign({}, BASE, { 3: shift(T.dark, -0.1, -0.03, 0) });
      if (tier >= 4) Object.assign(p, PEARL);
      else if (tier >= 3) Object.assign(p, GOLD);
      if (CLASS_PAL[name]) Object.assign(p, CLASS_PAL[name](tier));
      return p;
    };
  }
  const hd = (name, rows, layers, emis) => RS.defSprite(name, rows, { hd: true, size: [32, 32], pal: pal(name), layers, emis });

  hd('knight', [
    '',
    '',
    '',
    '',
    '...............1m',
    '.............11mmM',
    '.........1mmmmmmmmmmM',
    '........1mmmmmmmmmmmmM',
    '.......1mm1mmmmmmmmmmMM',
    '.......1mmmmmmmmmmmmmMM',
    '.......mmmmmmmmmmmmmmM2',
    '.......m22222222222222M',
    '.......m22yw22222yw222M',
    '.......m22gG22222gG222M',
    '.......mmmmMmMmMmMmmmMM',
    '........MmmmmmmmmmmmM2',
    '.........2MMMMMMMMMM2',
    '....1mmM2lccccccccccC21mmM',
    '...1mmmmMlcccggccccCC1mmmmM',
    '...mmmMM2lccgyygcccCC2Mm',
    '....M2222lcccgGccccCC2.1mmM',
    '....mMM22lcccccccCCCC2.MMM2',
    '.....M2.Ggggggyyggggg0',
    '........lcccccccccCCC3',
    '........lcc3ccccccCC33',
    '.........C33cc3cccC333',
    '.........1mmM....1mmM',
    '.........mmM2....mmM2',
    '........9bbbB...9bbbB',
    '........BBBB8...BBBB8',
  ], [
    { min: 0, x: 24, y: 3, rows: [
      '...w',
      '...wW',
      '...wW',
      '...wW',
      '...wW',
      '...wW',
      '...wW',
      '...wW',
      '...wW',
      '...wW',
      '...wW',
      '...wW',
      '...wW',
      '...wW',
      '...wW',
      '...wx',
      'GggyyggG',
      '...bB',
      '...bB',
      '...yG',
    ] },
    { min: 1, x: 13, y: 0, rows: [
      '..lc',
      '.llcC',
      '.lccC',
      'llcCC',
      'lcCC3',
      '.cC3',
    ] },
    { min: 2, x: 3, y: 17, rows: [
      '.yggG..............yggG',
      'g..................g',
      '',
      '',
      '',
      '',
      '',
      '',
      '......GggggggggggG0',
    ] },
    { min: 3, x: 6, y: 17, under: true, rows: [
      '..CCCCCCCCCCCCCC',
      '.CCCCCCCCCCCCCCC3',
      'CCCCCCCCCCCCCCCC33',
      'CCCCCCCCCCCCCCCC33',
      'CCCCCCCCCCCCCCCC33',
      'CCCCCCCCCCCCCCCC33',
      'CCCCCCCCCCCCCCCC33',
      'CCCCCCCCCCCCCCC333',
      'CCCCCCCCCCCCCCC333',
      'C3CCCCCCCCCCCCC33',
      '33CCC3CCCCC3CC33',
      '.3.33..3...333',
    ] },
    { min: 4, x: 0, y: 7, under: true, rows: [
      '.F............................f',
      'Ff............................ff',
      'Ffd..........................dff',
      'FfFd........................dfff',
      'fFfd........................dfff',
      'FffFd......................dffff',
      'fFffd......................dffff',
      '.FffFd....................dffff',
      '.fFffdd..................ddffff',
      '..fFffdd................ddffff',
      '...ffdd..................ddff',
      '....dd....................dd',
    ] },
  ], { 3: 'y', 4: 'yY' });

  hd('archer', [
    '',
    '',
    '............lccccc',
    '..........lcccccccccC',
    '.........lcllcccccccCC',
    '........lcllccccccccCC3',
    '.......lcllcccccccccCC3',
    '.......lclc6hhhhh6hccC3',
    '......lccc6hhhhhhhhhhcC3',
    '......lcc6hhhhhhhhhhhhC3',
    '......lch6sssssssssshhhC3',
    '......lchssssssssssssShC3',
    '......lcssewsssssewssSSC3',
    '......lcsseessssseessSSC3',
    '......lcSvssss55sssvSSSC3',
    '......lccSSsssssssSSScC3',
    '.......lccSSSSSSSSSScC3',
    '........lccccccccccccC3',
    '......lccQnnnnnnnnnnNcCss',
    '....lcccQnnnnnnnnnnNNcC3sS',
    '....lcccQnnn9bbnnnNNNcC3',
    '....lcccQnnnBBBnnnNNNcC3',
    '.....lccQnnnnnnnnnqqcC3',
    '......ccQnnnnnnnnqqC3',
    '.......CnnnnnnnnNqq3',
    '........NNnnnnnNNqq',
    '........9bbB....9bbB',
    '........bbbB....bbbB',
    '........BBB8....BBB8',
    '.........88......88',
  ], [
    { min: 0, x: 26, y: 4, rows: [
      '.uU',
      'W.uU',
      'W..uU',
      'W..uU',
      'W...uU',
      'W...uU',
      'W...uU',
      'W...uU',
      'W...uU',
      'W...uU',
      'W...uU',
      'W...uU',
      'W..uU',
      'W..uU',
      'W.uU',
      'WuU',
      'uU',
    ] },
    { min: 1, x: 3, y: 7, under: true, rows: [
      'r.w',
      'rrww',
      'G0Gg',
      '9bB',
      '9bB',
      '9bB',
      '9bB',
      '9bB',
      '9bB',
      '9bB',
      '9bB',
      'BB',
    ] },
    { min: 2, x: 6, y: 15, rows: [
      'g',
      '.g',
      '..GgggggyyggggG0',
    ] },
    { min: 3, x: 5, y: 18, under: true, rows: [
      '.CC...............C3',
      '',
      'CCCCCCCCCCCCCCCC33',
      'CCCCCCCCCCCCCCCC33',
      'CCCCCCCCCCCCCCCC33',
      'CCCCCCCCCCCCCCCC33',
      'CCCCCCCCCCCCCCCC33',
      'CCCCCCCCCCCCCCCC33',
      'CCCCCCCCCCCCCCCC33',
      'CCCCCCCCCCCCCCCC33',
      '.C3C..3C3..33',
    ] },
    { min: 4, x: 10, y: 0, under: true, rows: [
      '.YYYYYYYY',
      'Y........Y',
      '.YY......YY',
    ] },
  ], { 3: '', 4: 'Y' });

  hd('mage', [
    '.......lc',
    '.......lcc',
    '........lcc',
    '........lccC',
    '.........lccC',
    '.........llccC',
    '.........lccccC',
    '.........lcllccCC',
    '........lccllccccC3',
    '........lcccccccccC3',
    '.......lccyggggg0cC3',
    '......lcccGGGGGGcCC33',
    '..lllccccccccccccccccccccCC33',
    '...3CCCCCCCCCCCCCCCCCCCCC33',
    '......7hSSSSSSSSSSSSSSh7',
    '......6hsssssssssssssShH',
    '......6hssewsssssewsSShH',
    '......6hsseessssseesSShH',
    '......hhSvsssss55ssvSShH',
    '.......hHSSssssssSSSHH',
    '........lcccc5SSSS5cCCcCC3ss',
    '.......lccccccgyccccC3.CC3sS',
    '.......lcccccccgcccccC33',
    '......lcccccccc0ccccCC33',
    '......lccccccccccccccCC33',
    '.....lccccccccccccccccCC3',
    '.....lcccccccccccccccCCC33',
    '....lccccccccccccccccCCC333',
    '....3CCCCCCCCCCCCCCCCCCC33',
    '.....33333333333333333333',
  ], [
    { min: 0, x: 27, y: 3, rows: [
      '.pp',
      'pvpP',
      'pppP',
      '.PP',
      '.gG',
      '.9B',
      '.9B',
      '.9B',
      '.9B',
      '.9B',
      '.9B',
      '.9B',
      '.9B',
      '.9B',
      '.9B',
      '.9B',
      '.9B',
      '.9B',
      '.9B',
      '.9B',
      '.9B',
      '.9B',
      '.9B',
      '.9B',
      '.9B',
      '.9B',
    ] },
    { min: 1, x: 12, y: 5, rows: [
      '..y',
      'yyy',
      '.yy',
    ] },
    { min: 2, x: 2, y: 12, rows: [
      'yyg',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '..GggggggggggggggggggG0',
    ] },
    { min: 3, x: 14, y: 22, rows: [
      'yg',
      'gG',
      'gG',
      'gG',
      'gG',
      'gG',
    ] },
    { min: 4, x: 3, y: 0, under: true, rows: [
      '.....................Y',
      '',
      '.Y',
      'YYY',
      '.Y...............Y',
      '................YYY',
      '.................Y',
    ] },
  ], { 3: 'pv', 4: 'pvY' });

  hd('rogue', [
    '',
    '',
    '........6h....6h....hH',
    '........6hh..66hh..6hH',
    '........6hhhhhhhhhhhhhH',
    '.......6hhh6hhhhhhhhhhH',
    '.......6hh6hhhhhhhhhhhH7',
    '......6hh6hhhhhhhhhhhhH7',
    '......hhhhhssssssssShHH7',
    '......hhhsssssssssssShH7',
    '......hhssewsssssewsSSH7',
    '......hhsseessssseesSSH7',
    '......lcccccccccccccccC3',
    '.......lcccccccccccccCC3',
    '........lccCCcccccCCcC3',
    '........cccCCcccccCCC3',
    '........JkkkkkkkkkkkKK',
    '.......JJkkkkkkkkkkkkKKj',
    '....ssJkkkkkkkcckkkkkKKjss',
    '....sSJkkkkkkkcCkkkkkKKjSS',
    '......JkkkkkkkkkkkkkkKKj',
    '.......JkkkkkkkkkkkkKKj',
    '.......jbbBBbbbbbbBBbBj',
    '........jkKKkkkkkkKKkj',
    '........Jkkkk...kkkkK',
    '........kkkK.....kkkK',
    '........KKKj.....KKKj',
    '.........jj.......jj',
  ], [
    { min: 0, x: 1, y: 12, rows: [
      '.w.......................w',
      '.wW......................wW',
      '.wW......................wW',
      '.wx......................wx',
      'GggG....................GggG',
      '.bB......................bB',
    ] },
    { min: 1, x: 23, y: 10, under: true, rows: [
      'lc',
      '.lcC',
      '..lcC',
      '...cC',
      '....C',
    ] },
    { min: 2, x: 5, y: 16, rows: [
      '.1mM............1mM',
      '1mmM............1mMM',
      '',
      '',
      '',
      '',
      '........gyg',
    ] },
    { min: 3, x: 5, y: 17, under: true, rows: [
      'C',
      '.CCCCCCCCCCCCCCCCC3',
      '.CCCCCCCCCCCCCCCCC3',
      '.CCCCCCCCCCCCCCCCC3',
      '.CCCCCCCCCCCCCCCCC3',
      '.CCCCCCCCCCCCCCCCC3',
      '.CCCCCCCCCCCCCCCCC3',
      '.CCCCCCCCCCCCCCCCC3',
      '.CCCCCCCCCCCCCCCCC3',
      '.CCCCCCCCCCCCCCCCC3',
      '.C3.C3C..C3C.33',
    ] },
    { min: 4, x: 0, y: 8, under: true, rows: [
      '.D............................D',
      'DD............................DD',
      'DdD..........................DdD',
      'dDdD........................DdDd',
      'DdddD......................DdddD',
      'dDdddD....................DdddDd',
      '.dDddd....................dddDd',
      '..dDdd....................ddDd',
      '...ddd....................ddd',
      '....d......................d',
    ] },
  ], { 3: 'y', 4: 'ye' });

  hd('frost', [
    '',
    '',
    '.............zzzii',
    '...........zziiiiiii',
    '..........ziiiiiiiiiiI',
    '.........ziziiiiiiiiiiI',
    '.........zizziiiiiiiiiII',
    '........ziziiiiiiiiiiiII',
    '........zigyggggggyggGiI',
    '........iiG0GGGGGGGGG0II',
    '.......ziissssssssssSSiI',
    '.......ziissssssssssSSiII',
    '.......ziissewsssewsSSiII',
    '.......ziisseessseesSSiII',
    '.......ziiSvss55ssvSSSiII',
    '.......ziiISSssssSSSSIiII',
    '......ziiIcS5SSSS5cIiIZ',
    '......ziilccczzzzcccCiIZ',
    '......zilccccyGcccccCiIZ..ss',
    '......zilccccccccccccCIZ..sS',
    '......iIlcccccllcccccCIZ',
    '.......IlcccccllccccCCZ',
    '........lcccccccccccCC3',
    '.......lccccccccccccCC3',
    '.......lccccccccccccCCC3',
    '......lcccccccccccccCCC33',
    '......3CCCCCCCCCCCCCCCC33',
    '.......3333333333333333',
  ], [
    { min: 0, x: 26, y: 0, rows: [
      '.z',
      'z',
      '...z',
      '..zi',
      '.zziI',
      '.ziiI',
      '.ziIZ',
      '..IZ',
      '..gG',
      '..9B',
      '..9B',
      '..9B',
      '..9B',
      '..9B',
      '..9B',
      '..9B',
      '..9B',
      '..9B',
      '..9B',
      '..9B',
      '..9B',
      '..9B',
      '..9B',
      '..9B',
      '..9B',
      '..9B',
      '..9B',
    ] },
    { min: 1, x: 15, y: 7, rows: [
      'gg',
      'uu',
    ] },
    { min: 2, x: 9, y: 17, rows: [
      'zzzzzzzzzzzz',
      '.z.........Z',
    ] },
    { min: 3, x: 11, y: 4, rows: [
      'X...X...X',
      'Xi..Xi..Xi',
      'XiI.XI..XiI',
      'iIiiiIiiiI',
    ] },
    { min: 3, x: 4, y: 20, under: true, rows: [
      'CCCCCCCCCCCCCCCCCCCC33',
      'CCCCCCCCCCCCCCCCCCCC33',
      'CCCCCCCCCCCCCCCCCCCC33',
      'CCCCCCCCCCCCCCCCCCCC33',
      'CCCCCCCCCCCCCCCCCCCC33',
      'CCCCCCCCCCCCCCCCCCCC33',
      'CCCCCCCCCCCCCCCCCCCC33',
      '.C3.3C.3..C3.3C3.33',
    ] },
    { min: 4, x: 4, y: 0, under: true, rows: [
      '.....Y',
      '....YYY..........Y',
      '.....Y..........YYY',
      '.................Y',
      'Y',
    ] },
  ], { 3: 'Xu', 4: 'XuYe' });
})((globalThis.RS = globalThis.RS || {}));
